Fix git issue with prerelease job
Currently the prerelease job fails with:
```
error: The following untracked working tree files would be overwritten by checkout:
	nix-installer-aarch64-darwin
	nix-installer-aarch64-linux
	nix-installer-i686-linux
	nix-installer-x86_64-darwin
	nix-installer-x86_64-linux
```
https://github.com/NixOS/experimental-nix-installer/actions/runs/11708583897/job/32610685871

This is because assemble_installer.py adds those files on main, but then
the job tries to checkout prerelease.

Instead, fetch and checkout the prerelease branch in
assemble_installer.py before creating those files.